CONNECT TO TPCH_DB;
SET INTEGRITY FOR DB2INST1.ORDERS OFF;
LOAD FROM '/mnt/data/tpchdata/orders_1.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_2.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_3.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_4.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_5.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_6.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_7.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_8.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_9.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE; 
LOAD FROM '/mnt/data/tpchdata/orders_10.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_11.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_12.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_13.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_14.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_15.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_16.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_17.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_18.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_19.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_20.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_21.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_22.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_23.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_24.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/orders_25.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.orders NONRECOVERABLE;

SET INTEGRITY FOR DB2INST1.orders IMMEDIATE CHECKED;
