CONNECT TO TPCH_DB;
LOAD FROM 'E:\tpch\region_1.tbl' OF DEL MODIFIED BY coldel| nochardel INSERT INTO DB2ADMIN.REGION NONRECOVERABLE INDEXING MODE REBUILD;
LOAD FROM 'E:\tpch\nation_1.tbl' OF DEL MODIFIED BY coldel| nochardel INSERT INTO DB2ADMIN.NATION NONRECOVERABLE INDEXING MODE REBUILD;

SET INTEGRITY PENDING CASCADE DEFERRED;
