CONNECT TO TPCH_DB;

LOAD FROM '/mnt/data/tpchdata/region_1.tbl' OF DEL MODIFIED BY coldel| nochardel INSERT INTO DB2INST1.REGION NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/nation_1.tbl' OF DEL MODIFIED BY coldel| nochardel INSERT INTO DB2INST1.NATION NONRECOVERABLE;

SET INTEGRITY PENDING CASCADE DEFERRED;
