CONNECT TO TPCH_DB;
SET INTEGRITY FOR DB2INST1.SUPPLIER OFF;
LOAD FROM '/mnt/data/tpchdata/supplier_1.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_2.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_3.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_4.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_5.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_6.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_7.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_8.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_9.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_10.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_11.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_12.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_13.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_14.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_15.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_16.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_17.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_18.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_19.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_20.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_21.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_22.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_23.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_24.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/supplier_25.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.SUPPLIER NONRECOVERABLE;

SET INTEGRITY FOR DB2INST1.SUPPLIER IMMEDIATE CHECKED;