CONNECT TO TPCH_DB;
SET INTEGRITY FOR DB2INST1.PART OFF;
LOAD FROM '/mnt/data/tpchdata/part_1.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_2.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_3.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_4.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_5.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_6.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_7.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_8.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_9.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_10.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_11.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_12.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_13.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_14.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_15.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_16.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_17.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_18.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_19.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_20.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_21.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_22.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_23.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_24.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/part_25.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.PART NONRECOVERABLE;
SET INTEGRITY FOR DB2INST1.PART IMMEDIATE CHECKED;