CONNECT TO TPCH_DB;
SET INTEGRITY FOR DB2INST1.CUSTOMER OFF;
LOAD FROM '/mnt/data/tpchdata/customer_1.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_2.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_3.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_4.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_5.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_6.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_7.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_8.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_9.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_10.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_11.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_12.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_13.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_14.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_15.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_16.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_17.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_18.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_19.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_20.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_21.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_22.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_23.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_24.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;
LOAD FROM '/mnt/data/tpchdata/customer_25.tbl' OF DEL MODIFIED BY coldel| nochardel decpt=. keepblanks SAVECOUNT 100000 INSERT INTO DB2INST1.CUSTOMER NONRECOVERABLE;

SET INTEGRITY FOR DB2INST1.CUSTOMER IMMEDIATE CHECKED;