DROP TABLESPACE MASTER_IDX_TS;
DROP TABLESPACE ORDERS_IDX_TS;
DROP TABLESPACE LINEITEM_IDX_TS;
DROP TABLESPACE LOOKUP_IDX_TS;

-- Index tablespace for lookup tables
CREATE TABLESPACE LOOKUP_IDX_TS
  PAGESIZE 16K
  MANAGED BY AUTOMATIC STORAGE
  BUFFERPOOL BP_LOOKUP;

-- Index tablespace for master data
CREATE TABLESPACE MASTER_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  BUFFERPOOL BP_MASTER;

-- Index tablespace for ORDERS
CREATE TABLESPACE ORDERS_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  BUFFERPOOL BP_TRANS;

-- Index tablespace for LINEITEM
CREATE TABLESPACE LINEITEM_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  BUFFERPOOL BP_TRANS;