DROP TABLE "DB2ADMIN"."CUSTOMER";
DROP TABLE "DB2ADMIN"."LINEITEM";
DROP TABLE "DB2ADMIN"."NATION";
DROP TABLE "DB2ADMIN"."ORDERS";
DROP TABLE "DB2ADMIN"."PART";
DROP TABLE "DB2ADMIN"."PARTSUPP";
DROP TABLE "DB2ADMIN"."REGION";
DROP TABLE "DB2ADMIN"."SUPPLIER";
DROP TABLESPACE "TPCH_DATA_TS";
DROP BUFFERPOOL BP_32K;
--CONNECT TO TPCH;
-- Adjust size based on RAM. 100000 pages = ~3.2GB.
--CREATE BUFFERPOOL BP_32K SIZE 100000 PAGESIZE 32 K;

CREATE LARGE TABLESPACE TPCH_DATA_TS
  PAGESIZE 32 K
  MANAGED BY AUTOMATIC STORAGE;
--  BUFFERPOOL BP_32K
--  -- Tune these for your storage (SSD usually has lower overhead)
--  OVERHEAD 7.5
--  -- Tune these for your storage
--  TRANSFERRATE 0.06 ;

CREATE TABLE "DB2ADMIN"."CUSTOMER" (
		"C_CUSTKEY" INTEGER NOT NULL, 
		"C_MKTSEGMENT" CHAR(10) NOT NULL, 
		"C_NATIONKEY" INTEGER NOT NULL, 
		"C_NAME" VARCHAR(25) NOT NULL, 
		"C_ADDRESS" VARCHAR(40) NOT NULL, 
		"C_PHONE" CHAR(15) NOT NULL, 
		"C_ACCTBAL" CHAR(20) NOT NULL, 
		"C_COMMENT" VARCHAR(118) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."LINEITEM" (
		"L_SHIPDATE" CHAR(20),
		"L_LINENUMBER" BIGINT NOT NULL, 
		"L_DISCOUNT" CHAR(10) NOT NULL, 
		"L_EXTENDEDPRICE" CHAR(20) NOT NULL,
		"L_ORDERKEY" BIGINT NOT NULL, 
		"L_QUANTITY" char(20) NOT NULL, 
		"L_RETURNFLAG" CHAR(1) NOT NULL,
		"L_PARTKEY" BIGINT NOT NULL, 
		"L_LINESTATUS" CHAR(1) NOT NULL,
		"L_TAX" CHAR(20) NOT NULL,
		"L_RECEIPTDATE" CHAR(20),
		"L_COMMITDATE" CHAR(20), 
		"L_SHIPMODE" CHAR(10) NOT NULL,
		"L_SUPPKEY" BIGINT NOT NULL, 
		"L_SHIPINSTRUCT" CHAR(25) NOT NULL, 
		"L_COMMENT" VARCHAR(44) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."NATION" (
		"N_NATIONKEY" INTEGER NOT NULL, 
		"N_NAME" CHAR(25) NOT NULL, 
		"N_REGIONKEY" INTEGER NOT NULL, 
		"N_COMMENT" VARCHAR(152)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."ORDERS" (
		"O_ORDERDATE" CHAR(20) NOT NULL, 
		"O_ORDERKEY" BIGINT NOT NULL, 
		"O_CUSTKEY" BIGINT NOT NULL, 
		"O_ORDERPRIORITY" CHAR(15) NOT NULL,
		"O_SHIPPRIORITY" INTEGER,
		"O_CLERK" CHAR(25) NOT NULL,
		"O_ORDERSTATUS" CHAR(1) NOT NULL,
		"O_TOTALPRICE" CHAR(20) NOT NULL, 
		"O_COMMENT" VARCHAR(79) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."PART" (
		"P_PARTKEY" INTEGER NOT NULL, 
		"P_NAME" VARCHAR(55) NOT NULL, 
		"P_SIZE" INTEGER NOT NULL,
		"P_BRAND" CHAR(10) NOT NULL, 
		"P_TYPE" VARCHAR(50) NOT NULL, 
		"P_CONTAINER" CHAR(10) NOT NULL, 
		"P_MFGR" CHAR(25) NOT NULL, 
		"P_RETAILPRICE" CHAR(20) NOT NULL, 
		"P_COMMENT" VARCHAR(23)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."PARTSUPP" (
		"PS_PARTKEY" INTEGER NOT NULL, 
		"PS_SUPPKEY" INTEGER NOT NULL, 
		"PS_SUPPLYCOST" CHAR(20) NOT NULL, 
		"PS_AVAILQTY" INTEGER NOT NULL, 
		"PS_COMMENT" VARCHAR(199) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."REGION" (
		"R_REGIONKEY" INTEGER NOT NULL, 
		"R_NAME" CHAR(25) NOT NULL, 
		"R_COMMENT" VARCHAR(152)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

CREATE TABLE "DB2ADMIN"."SUPPLIER" (
		"S_SUPPKEY" INTEGER NOT NULL, 
		"S_NATIONKEY" INTEGER NOT NULL,
		"S_COMMENT" VARCHAR(102) NOT NULL,
		"S_NAME" CHAR(25) NOT NULL, 
		"S_ADDRESS" VARCHAR(40) NOT NULL, 
		"S_PHONE" CHAR(15) NOT NULL, 
		"S_ACCTBAL" CHAR(20) NOT NULL
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "TPCH_DATA_TS"
	COMPRESS NO;

GRANT ALTER ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT ALTER ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT CONTROL ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN";

GRANT CONTROL ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN";

GRANT DELETE ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT DELETE ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INDEX ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT INSERT ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT SELECT ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."CUSTOMER" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."LINEITEM" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."NATION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."ORDERS" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."PART" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."PARTSUPP" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."REGION" TO USER "DB2ADMIN" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "DB2ADMIN"."SUPPLIER" TO USER "DB2ADMIN" WITH GRANT OPTION;

