-- DROP TABLESPACE LOOKUP_TS;
-- DROP TABLESPACE MASTER_TS;
-- DROP TABLESPACE ORDERS_TS;
-- DROP TABLESPACE LINEITEM_TS;

-- Tablespace for small lookup tables (REGION, NATION)
CREATE TABLESPACE LOOKUP_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE;

-- Tablespace for master data (CUSTOMER, SUPPLIER, PART, PARTSUPP)
CREATE TABLESPACE MASTER_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE;

-- Tablespace for ORDERS table
CREATE TABLESPACE ORDERS_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE;
  
-- Tablespace for LINEITEM table
CREATE LARGE TABLESPACE LINEITEM_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE;