-- Index tablespace for lookup tables
CREATE TABLESPACE LOOKUP_IDX_TS
  PAGESIZE 16K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 128M
  INCREASESIZE 64M
  BUFFERPOOL BP_LOOKUP
  FOR INDEXES;

-- Index tablespace for master data
CREATE TABLESPACE MASTER_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 32G
  INCREASESIZE 16G
  PREFETCHSIZE 512
  BUFFERPOOL BP_MASTER;

-- Index tablespace for ORDERS
CREATE TABLESPACE ORDERS_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 64G
  INCREASESIZE 32G
  PREFETCHSIZE 1024
  BUFFERPOOL BP_TRANS;

-- Index tablespace for LINEITEM
CREATE TABLESPACE LINEITEM_IDX_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 256G
  INCREASESIZE 64G
  PREFETCHSIZE 2048
  BUFFERPOOL BP_TRANS;