-- REGION table
CREATE TABLE REGION (
    R_REGIONKEY INTEGER NOT NULL,
    R_NAME      CHAR(25) NOT NULL,
    R_COMMENT   VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
) IN LOOKUP_TS
  INDEX IN LOOKUP_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- NATION table
CREATE TABLE NATION (
    N_NATIONKEY INTEGER NOT NULL,
    N_NAME      CHAR(25) NOT NULL,
    N_REGIONKEY INTEGER NOT NULL,
    N_COMMENT   VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY),
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
) IN LOOKUP_TS
  INDEX IN LOOKUP_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- SUPPLIER table
CREATE TABLE SUPPLIER (
    S_SUPPKEY   INTEGER NOT NULL,
    S_NATIONKEY INTEGER NOT NULL,
    S_COMMENT   VARCHAR(101),
    S_NAME      CHAR(25) NOT NULL,
    S_ADDRESS   VARCHAR(40) NOT NULL,  
    S_PHONE     CHAR(15) NOT NULL,
    S_ACCTBAL   CHAR(15) NOT NULL,
    PRIMARY KEY (S_SUPPKEY),
    FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
) IN MASTER_TS
  INDEX IN MASTER_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- PART table
CREATE TABLE PART (
    P_PARTKEY     INTEGER NOT NULL,
    P_NAME        VARCHAR(55) NOT NULL,
    P_SIZE        INTEGER NOT NULL,
    P_BRAND       CHAR(10) NOT NULL,
    P_TYPE        VARCHAR(30) NOT NULL,
    P_CONTAINER   CHAR(10) NOT NULL,
    P_RETAILPRICE CHAR(15) NOT NULL,
    P_MFGR        CHAR(25) NOT NULL,
    P_COMMENT     VARCHAR(23),
    PRIMARY KEY (P_PARTKEY)
) IN MASTER_TS
  INDEX IN MASTER_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- PARTSUPP table
CREATE TABLE PARTSUPP (
    PS_PARTKEY    INTEGER NOT NULL,
    PS_SUPPKEY    INTEGER NOT NULL,
    PS_AVAILQTY   INTEGER NOT NULL,
    PS_SUPPLYCOST DECIMAL(15,2) NOT NULL,
    PS_COMMENT    VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
    FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
) IN MASTER_TS
  INDEX IN MASTER_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- CUSTOMER table
CREATE TABLE CUSTOMER (
    C_CUSTKEY    INTEGER NOT NULL,
    C_NAME       VARCHAR(25) NOT NULL,
    C_ADDRESS    VARCHAR(40) NOT NULL,
    C_NATIONKEY  INTEGER NOT NULL,
    C_PHONE      CHAR(15) NOT NULL,
    C_ACCTBAL    CHAR(15) NOT NULL,
    C_MKTSEGMENT CHAR(10) NOT NULL,
    C_COMMENT    VARCHAR(117),
    PRIMARY KEY (C_CUSTKEY),
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
) IN MASTER_TS
  INDEX IN MASTER_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- ORDERS table
CREATE TABLE ORDERS (
    O_ORDERKEY       INTEGER NOT NULL,
    O_CUSTKEY        INTEGER NOT NULL,
    O_ORDERSTATUS    CHAR(1) NOT NULL,
    O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
    O_ORDERDATE      DATE NOT NULL,
    O_ORDERPRIORITY  CHAR(15) NOT NULL,
    O_CLERK          CHAR(15) NOT NULL,
    O_SHIPPRIORITY   INTEGER NOT NULL,
    O_COMMENT        VARCHAR(79),
    PRIMARY KEY (O_ORDERKEY),
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
) IN ORDERS_TS
  INDEX IN ORDERS_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES;

-- LINEITEM table
CREATE TABLE LINEITEM (
    L_ORDERKEY       INTEGER NOT NULL,
    L_PARTKEY        INTEGER NOT NULL,
    L_SUPPKEY        INTEGER NOT NULL,
    L_LINENUMBER     INTEGER NOT NULL,
    L_QUANTITY       DECIMAL(15,2) NOT NULL,
    L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
    L_DISCOUNT       DECIMAL(15,2) NOT NULL,
    L_TAX            DECIMAL(15,2) NOT NULL,
    L_RETURNFLAG     CHAR(1) NOT NULL,
    L_LINESTATUS     CHAR(1) NOT NULL,
    L_SHIPDATE       DATE NOT NULL,
    L_COMMITDATE     DATE NOT NULL,
    L_RECEIPTDATE    DATE NOT NULL,
    L_SHIPINSTRUCT   CHAR(25) NOT NULL,
    L_SHIPMODE       CHAR(10) NOT NULL,
    L_COMMENT        VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY)
) IN LINEITEM_TS
  INDEX IN LINEITEM_IDX_TS
  ORGANIZE BY ROW
  COMPRESS YES
   PARTITION BY RANGE(L_SHIPDATE)
  (PARTITION P_PRE2018 STARTING FROM ('0001-01-01') INCLUSIVE ENDING AT ('2018-01-01') EXCLUSIVE,
   PARTITION P_2018 STARTING FROM ('2018-01-01') INCLUSIVE ENDING AT ('2019-01-01') EXCLUSIVE,
   PARTITION P_2019 STARTING FROM ('2019-01-01') INCLUSIVE ENDING AT ('2020-01-01') EXCLUSIVE,
   PARTITION P_2020 STARTING FROM ('2020-01-01') INCLUSIVE ENDING AT ('2021-01-01') EXCLUSIVE,
   PARTITION P_2021 STARTING FROM ('2021-01-01') INCLUSIVE ENDING AT ('2022-01-01') EXCLUSIVE,
   PARTITION P_2022 STARTING FROM ('2022-01-01') INCLUSIVE ENDING AT ('2023-01-01') EXCLUSIVE,
   PARTITION P_2023 STARTING FROM ('2023-01-01') INCLUSIVE ENDING AT ('2024-01-01') EXCLUSIVE,
   PARTITION P_2024 STARTING FROM ('2024-01-01') INCLUSIVE ENDING AT ('2025-01-01') EXCLUSIVE,
   PARTITION P_FUTURE STARTING FROM ('2025-01-01') INCLUSIVE ENDING AT ('9999-12-31') INCLUSIVE);

-- Create indexes for performance
CREATE INDEX IDX_CUSTOMER_NATION ON CUSTOMER(C_NATIONKEY);
CREATE INDEX IDX_SUPPLIER_NATION ON SUPPLIER(S_NATIONKEY);
CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(O_CUSTKEY);
CREATE INDEX IDX_LINEITEM_ORDER ON LINEITEM(L_ORDERKEY);
CREATE INDEX IDX_LINEITEM_PART_SUPP ON LINEITEM(L_PARTKEY, L_SUPPKEY);
CREATE INDEX IDX_NATION_REGION ON NATION(N_REGIONKEY);