-- Tablespace for small lookup tables (REGION, NATION)
CREATE TABLESPACE LOOKUP_TS
  PAGESIZE 16K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 256M
  INCREASESIZE 128M
  BUFFERPOOL BP_LOOKUP
  OVERHEAD 10.5
  TRANSFERRATE 0.14
  DROPPED TABLE RECOVERY ON;

-- Tablespace for master data (CUSTOMER, SUPPLIER, PART, PARTSUPP)
CREATE TABLESPACE MASTER_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 128G 
  INCREASESIZE 32G
  EXTENTSIZE 256
  PREFETCHSIZE 512
  BUFFERPOOL BP_MASTER
  OVERHEAD 7.5
  TRANSFERRATE 0.1
  DROPPED TABLE RECOVERY ON;

-- Tablespace for ORDERS table
CREATE TABLESPACE ORDERS_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 256G
  INCREASESIZE 64G
  EXTENTSIZE 256
  PREFETCHSIZE 1024
  BUFFERPOOL BP_TRANS
  OVERHEAD 7.5
  TRANSFERRATE 0.1
  DROPPED TABLE RECOVERY ON;

-- Tablespace for LINEITEM table
CREATE TABLESPACE LINEITEM_TS
  PAGESIZE 32K
  MANAGED BY AUTOMATIC STORAGE
  INITIALSIZE 1024G
  INCREASESIZE 256G
  EXTENTSIZE 256
  PREFETCHSIZE 2048
  BUFFERPOOL BP_TRANS
  OVERHEAD 7.5
  TRANSFERRATE 0.1
  DROPPED TABLE RECOVERY ON;