DECLARE @Counter AS INT
DECLARE @LoopCount AS INT
SET @COUNTER = 0
SET @LoopCount = 10
WHILE (
        SELECT @Counter
        ) < @LoopCount
BEGIN
	BULK INSERT customer FROM 'C:\mnt\tpchdata\customer_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT lineitem FROM 'C:\mnt\tpchdata\lineitem_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT orders   FROM 'C:\mnt\tpchdata\orders_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT part     FROM 'C:\mnt\tpchdata\part_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT partsupp FROM 'C:\mnt\tpchdata\partsupp_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT supplier FROM 'C:\mnt\tpchdata\supplier_1.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	--
	BULK INSERT customer FROM 'C:\mnt\tpchdata\customer_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT lineitem FROM 'C:\mnt\tpchdata\lineitem_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT orders   FROM 'C:\mnt\tpchdata\orders_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT part     FROM 'C:\mnt\tpchdata\part_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT partsupp FROM 'C:\mnt\tpchdata\partsupp_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT supplier FROM 'C:\mnt\tpchdata\supplier_2.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	--
	BULK INSERT customer FROM 'C:\mnt\tpchdata\customer_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT lineitem FROM 'C:\mnt\tpchdata\lineitem_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT orders   FROM 'C:\mnt\tpchdata\orders_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT part     FROM 'C:\mnt\tpchdata\part_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT partsupp FROM 'C:\mnt\tpchdata\partsupp_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT supplier FROM 'C:\mnt\tpchdata\supplier_3.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	--
	BULK INSERT customer FROM 'C:\mnt\tpchdata\customer_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT lineitem FROM 'C:\mnt\tpchdata\lineitem_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT orders   FROM 'C:\mnt\tpchdata\orders_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT part     FROM 'C:\mnt\tpchdata\part_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT partsupp FROM 'C:\mnt\tpchdata\partsupp_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT supplier FROM 'C:\mnt\tpchdata\supplier_4.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	--
	BULK INSERT customer FROM 'C:\mnt\tpchdata\customer_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT lineitem FROM 'C:\mnt\tpchdata\lineitem_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT orders   FROM 'C:\mnt\tpchdata\orders_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT part     FROM 'C:\mnt\tpchdata\part_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT partsupp FROM 'C:\mnt\tpchdata\partsupp_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)
	BULK INSERT supplier FROM 'C:\mnt\tpchdata\supplier_5.tbl' WITH (FIELDTERMINATOR = '|', TABLOCK, BATCHSIZE = 1000000, ROWS_PER_BATCH = 1000000)

    SET @Counter = @Counter + 1
	Print 'Finished Load ' + CAST(@Counter AS VARCHAR(20))
END