-- -- # SQL Schema Statements for TPC-H Database in MySQL
-- drop database tpch;
-- -- Here are the SQL schema statements for creating the TPC-H database tables in MySQL:
-- CREATE DATABASE tpch;
-- USE tpch;

-- CREATE TABLE NATION (
--     N_NATIONKEY INTEGER NOT NULL,
--     N_NAME CHAR(25) NOT NULL,
--     N_REGIONKEY INTEGER NOT NULL,
--     N_COMMENT VARCHAR(152),
--     PRIMARY KEY (N_NATIONKEY)
-- );

-- CREATE TABLE REGION (
--     R_REGIONKEY INTEGER NOT NULL,
--     R_NAME CHAR(25) NOT NULL,
--     R_COMMENT VARCHAR(152),
--     PRIMARY KEY (R_REGIONKEY)
-- );

-- CREATE TABLE PART (
--     P_PARTKEY INTEGER NOT NULL,
--     P_NAME VARCHAR(55) NOT NULL,
--     P_SIZE INTEGER NOT NULL,
--     P_BRAND CHAR(10) NOT NULL,
--     P_TYPE VARCHAR(100) NOT NULL,
--     P_CONTAINER CHAR(10) NOT NULL,
--     P_MFGR CHAR(25) NOT NULL,
--     P_RETAILPRICE DECIMAL(15,2) NOT NULL,
--     P_COMMENT VARCHAR(123) NOT NULL,
--     PRIMARY KEY (P_PARTKEY)
-- );

-- CREATE TABLE SUPPLIER (
--     S_SUPPKEY INTEGER NOT NULL,
--     S_NATIONKEY INTEGER NOT NULL,
--     S_COMMENT VARCHAR(150) NOT NULL,
--     S_NAME CHAR(25) NOT NULL,
--     S_ADDRESS VARCHAR(40) NOT NULL,
--     S_PHONE CHAR(15) NOT NULL,
--     S_ACCTBAL DECIMAL(15,2) NOT NULL,
--     PRIMARY KEY (S_SUPPKEY) 
--     -- FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
-- );
-- -- drop table PARTSUPP;
-- CREATE TABLE PARTSUPP (
--     PS_PARTKEY INTEGER NOT NULL,
--     PS_SUPPKEY INTEGER NOT NULL,
--     PS_AVAILQTY INTEGER NOT NULL,
--     PS_SUPPLYCOST DECIMAL(15,2) NOT NULL,
--     PS_COMMENT VARCHAR(299) NOT NULL,
--     PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
--     -- FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
--     -- FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
-- );
-- -- drop table CUSTOMER;
-- CREATE TABLE CUSTOMER (
--     C_CUSTKEY INTEGER NOT NULL,
--     C_MKTSEGMENT CHAR(10) NOT NULL,
--     C_NATIONKEY INTEGER NOT NULL,
--     C_NAME VARCHAR(25) NOT NULL,
--     C_ADDRESS VARCHAR(40) NOT NULL,
--     C_PHONE CHAR(15) NOT NULL,
--     C_ACCTBAL DECIMAL(15,2) NOT NULL,
--     C_COMMENT VARCHAR(150) NOT NULL,
--     PRIMARY KEY (C_CUSTKEY),
--     FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
-- );
drop table ORDERS;
CREATE TABLE ORDERS (
    O_ORDERDATE VARCHAR(12) NOT NULL,
    O_ORDERKEY BIGINT NOT NULL,
    O_CUSTKEY INTEGER NOT NULL,
    O_ORDERPRIORITY CHAR(15) NOT NULL,
    O_SHIPPRIORITY INTEGER NOT NULL,
    O_CLERK CHAR(15) NOT NULL,
    O_ORDERSTATUS CHAR(1) NOT NULL,
    O_TOTALPRICE DECIMAL(15,2) NOT NULL,
    O_COMMENT VARCHAR(179) NOT NULL,
    PRIMARY KEY (O_ORDERKEY)
    -- FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);
drop table LINEITEM;
CREATE TABLE LINEITEM (
    L_ORDERKEY BIGINT NOT NULL,
    L_PARTKEY INTEGER NOT NULL,
    L_SUPPKEY INTEGER NOT NULL,
    L_LINENUMBER INTEGER NOT NULL,
    L_QUANTITY DECIMAL(15,2) NOT NULL,
    L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL,
    L_DISCOUNT DECIMAL(15,2) NOT NULL,
    L_TAX DECIMAL(15,2) NOT NULL,
    L_RETURNFLAG CHAR(1) NOT NULL,
    L_LINESTATUS CHAR(1) NOT NULL,
    L_SHIPDATE DATE NOT NULL,
    L_COMMITDATE DATE NOT NULL,
    L_RECEIPTDATE DATE NOT NULL,
    L_SHIPINSTRUCT CHAR(25) NOT NULL,
    L_SHIPMODE CHAR(10) NOT NULL,
    L_COMMENT VARCHAR(44) NOT NULL,
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER, L_SHIPDATE)
    -- FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    -- FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY)
);
-- Consider PARTITION for very large tables
ALTER TABLE LINEITEM
PARTITION BY RANGE (YEAR(L_SHIPDATE)) (
    PARTITION p1992 VALUES LESS THAN (1993),
    PARTITION p1993 VALUES LESS THAN (1994),
    PARTITION p1994 VALUES LESS THAN (1995),
    PARTITION p1995 VALUES LESS THAN (1996),
    PARTITION p1996 VALUES LESS THAN (1997),
    PARTITION p1997 VALUES LESS THAN (1998),
    PARTITION p1998 VALUES LESS THAN (MAXVALUE)
);
-- Add indexes to improve query performance
CREATE INDEX IDX_CUSTOMER_NATION ON CUSTOMER(C_NATIONKEY);
CREATE INDEX IDX_SUPPLIER_NATION ON SUPPLIER(S_NATIONKEY);
CREATE INDEX IDX_LINEITEM_ORDER ON LINEITEM(L_ORDERKEY);
CREATE INDEX IDX_LINEITEM_PART_SUPP ON LINEITEM(L_PARTKEY, L_SUPPKEY);
CREATE INDEX IDX_LINEITEM_SHIPDATE ON LINEITEM(L_SHIPDATE);
CREATE INDEX IDX_ORDERS_CUSTKEY ON ORDERS(O_CUSTKEY);
CREATE INDEX IDX_ORDERS_ORDERDATE ON ORDERS(O_ORDERDATE);
CREATE INDEX IDX_NATION_REGION ON NATION(N_REGIONKEY);


-- These statements create the standard TPC-H schema with appropriate data types for MySQL, primary keys, foreign keys, and indexes to improve query performance. The TPC-H schema consists of eight tables representing a wholesale supplier's sales data.

