IMPORT FROM CSV FILE '/mnt/tpchdata/customer_1.tbl' INTO TPCH.customer WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/mnt/tpchdata/customer_2.tbl' INTO TPCH.customer WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/mnt/tpchdata/customer_3.tbl' INTO TPCH.customer WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/mnt/tpchdata/customer_4.tbl' INTO TPCH.customer WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/mnt/tpchdata/customer_5.tbl' INTO TPCH.customer WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';

IMPORT FROM CSV FILE '/mnt/tpchdata/lineitem_1.tbl' INTO TPCH.lineitem WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/lineitem_1.tbl' INTO TPCH.lineitem WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',';  
IMPORT FROM CSV FILE '/mnt/tpchdata/lineitem_1.tbl' INTO TPCH.lineitem WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/lineitem_1.tbl' INTO TPCH.lineitem WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/lineitem_1.tbl' INTO TPCH.lineitem WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/nation_1.tbl' INTO  TPCH.nation WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/orders_1.tbl' INTO TPCH.orders WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/orders_2.tbl' INTO TPCH.orders WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/orders_3.tbl' INTO TPCH.orders WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/orders_4.tbl' INTO TPCH.orders WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/orders_5.tbl' INTO TPCH.orders WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/part_1.tbl' INTO TPCH.part WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/part_2.tbl' INTO TPCH.part WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/part_3.tbl' INTO TPCH.part WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/part_4.tbl' INTO TPCH.part WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/part_5.tbl' INTO TPCH.part WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/partsupp_1.tbl' INTO TPCH.partsupp WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/partsupp_2.tbl' INTO TPCH.partsupp WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/partsupp_3.tbl' INTO TPCH.partsupp WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/partsupp_4.tbl' INTO TPCH.partsupp WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/partsupp_5.tbl' INTO TPCH.partsupp WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/region_1.tbl' INTO TPCH.region WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 

IMPORT FROM CSV FILE '/mnt/tpchdata/supplier_1.tbl' INTO TPCH.supplier WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/supplier_2.tbl' INTO TPCH.supplier WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/supplier_3.tbl' INTO TPCH.supplier WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/supplier_4.tbl' INTO TPCH.supplier WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 
IMPORT FROM CSV FILE '/mnt/tpchdata/supplier_5.tbl' INTO TPCH.supplier WITH RECORD DELIMITED BY '\n' FIELD DELIMITED BY ','; 